export const BLANK_C = {
  id: null,
  name: "",
  contactName: "",
  category: "Privado",
  email: "",
  phone: "",
  whatsapp: "",
  city: "",
  state: "",
  address: "",
  notes: "",
  alreadyBought: false,
  quotedNotBought: false,
  mainDepartment: "",
  departments: [],
  pagRazaoSocial: "",
  pagName: "",
  pagEmail: "",
  pagWhatsapp: "",
  pagPhone: "",
  pagEndereco: "",
  pagCNPJ: "",
  pagInscMunicipal: "",
  pagInscEstadual: "",
};

export const BLANK_LEAD = {
  id: null,
  contactName: "",
  organization: "",
  canal: "Contato",
  status: "Aguardando Proposta",
  startDate: "",
  notes: "",
  followUp: "",
  department: "",
  statusHistory: [],
};

export const BLANK_A = {
  id: null,
  types: [],
  type: "",
  format: "Presencial",
  client: "",
  clientCategory: "",
  department: "",
  departmentContact: "",
  paymentName: "",
  paymentEmail: "",
  paymentWhatsapp: "",
  paymentPhone: "",
  startDate: "",
  endDate: "",
  startTime: "",
  endTime: "",
  typeSchedules: {},
  city: "",
  state: "",
  status: "Proposta Enviada",
  value: "",
  tax: "10",
  expenses: [],
  notes: "",
};

export const EXP_F = {
  tipo: "Passagem Aérea",
  descricao: "",
  valor: "",
};
